### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by Its-Vichy** [Its-Vichy/HBot#1]
Hi _everyone_,
I am currently working on a **complete rewrite** of the server and loader as well as the scanner.
If the repo doesn't change for a while, don't worries!

If you have any _suggestions_ / _questions_, post them in replies to **this** post.

**Comment by Its-Vichy** [comment]
> Hi everyone, new HBot update soon, if you have any suggestions create issue / pull requests or send me mail `its_vichy@protonmail.com`., I have new discord acc btw i don't want to get banned another time (lol).
> 
> ```css
> + SSH Brutter (scanner)
> + HTTP File Server
> + SSH infection (loader)
> + Honeypot detection (add new detection method (because SSH honeypot bypass the first))
> ```
> 
> __For all dumb kid say "can you help me to setup the botnet"__, please read the *README.md*
>  I think this update comming this week.

**Comment by badboycxcc** [comment]
Hello, when will the new version be released?

**Comment by Its-Vichy** [comment]
Idk, i don't work anymore on it, maybe later..

**Comment by k3n4i70** [comment]
> Hi _everyone_, I am currently working on a **complete rewrite** of the server and loader as well as the scanner. If the repo doesn't change for a while, don't worries!
> 
> If you have any _suggestions_ / _questions_, post them in replies to **this** post.

Hi I can't find RunMaster.sh How I can find it

**Comment by sinaj2889** [comment]
> > Hi _everyone_, I am currently working on a **complete rewrite** of the server and loader as well as the scanner. If the repo doesn't change for a while, don't worries!
> > 
> > If you have any _suggestions_ / _questions_, post them in replies to **this** post.
> 
> Hi I can't find RunMaster.sh How I can find it

Too

**Comment by xor5** [comment]
i think its not getting updated
