### ISSUE TITLE
Tutorial Installing

### ISSUE THREAD

**Issue by Sn8ow** [Its-Vichy/HBot#2]
Make tutorial on youtube or on github please ?

**Comment by Its-Vichy** [comment]
There is no tutorials for the moment, 
The project is under developpement, The tutorials comming soon.

**Comment by Sn8ow** [comment]
@Its-Vichy Okay i wait...

**Comment by JokersCat** [comment]
still waiting.... xD

**Comment by Its-Vichy** [comment]
;-;
