### ISSUE TITLE
RunMaster

### ISSUE THREAD

**Issue by noscopepro** [Its-Vichy/HBot#4]
I was wondering there are no files under the name of RunMaster anywhere after i run the Intall.sh. How would i go about fixing this?

**Comment by Its-Vichy** [comment]
i don't provide help for dumb kid & you lost your time

**Comment by mypassistoor** [comment]
> i don't provide help for dumb kid & you lost your time

Dumb kid but you include directions for a file that isnt even generated no matter what.

**Comment by Its-Vichy** [comment]
If you have a minimum of brain you have just to read the code to understand

**Comment by mypassistoor** [comment]
> If you have a minimum of brain you have just to read the code to understand

If I have a minimum of a brain. Its funny that you tell me this but yet you cant even spell or make a script create a file on execution. I run Install.sh and literally nothing happens besides it updating and installing o bunch of things that are required for the net to be made. At the end no script named RunMaster is anywhere to be found.
